#!/usr/bin/env npx tsx
/**
 * memory-contextpack.ts — Auto-generate SCOPE.md context packs for agents.
 *
 * Reads the memory DB, fetches top-N facts by weight for each agent's home scopes,
 * and writes a formatted context pack to agents/{type}/SCOPE.md.
 *
 * Usage:
 *   npx tsx scripts/memory-contextpack.ts              # regenerate all
 *   npx tsx scripts/memory-contextpack.ts protocol-engineer  # regenerate one
 */

import { getMemoryDb, ensureSchema, listFacts, type FactRow, type Scope } from "./memory-db.ts";
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const AGENTS_DIR = join(__dirname, "..", "agents");

interface AgentDef {
    name: string;
    homeScopes: Scope[];
}

function readAgentDefs(): AgentDef[] {
    const agents: AgentDef[] = [];

    if (!existsSync(AGENTS_DIR)) { return agents; }

    const agentDirs = readdirSync(AGENTS_DIR, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name);

    for (const dir of agentDirs) {
        const agentMd = join(AGENTS_DIR, dir, "AGENT.md");
        if (!existsSync(agentMd)) { continue; }

        const content = readFileSync(agentMd, "utf8");
        const scopeMatch = content.match(/^home_scope:\s*(.+)$/m);
        if (!scopeMatch) { continue; }

        const scopes = scopeMatch[1]!.split(",").map((s) => s.trim()) as Scope[];
        agents.push({ name: dir, homeScopes: scopes });
    }

    return agents;
}

function generateContextPack(agent: AgentDef, factsByScope: Map<Scope, FactRow[]>): string {
    const now = new Date().toISOString().replace("T", " ").slice(0, 19);

    // Collect top-15 facts across all home scopes
    const allFacts: FactRow[] = [];
    for (const scope of agent.homeScopes) {
        const facts = factsByScope.get(scope) ?? [];
        allFacts.push(...facts);
    }
    allFacts.sort((a, b) => b.weight - a.weight);
    const topFacts = allFacts.slice(0, 15);

    let out = `# ${agent.name} — Context Pack\n\n`;
    out += `> Auto-generated by scripts/memory-contextpack.ts on ${now}\n`;
    out += `> Home scope(s): ${agent.homeScopes.join(", ")}\n\n`;
    out += `## Scope Declaration\n`;
    out += `You are the **${agent.name}**. Your home scope is ${agent.homeScopes.join(", ")}.\n\n`;

    if (topFacts.length === 0) {
        out += `## Essential Facts\n\nNo facts in scope yet. The memory DB needs seeding.\n`;
        return out;
    }

    out += `## Essential Facts (top ${topFacts.length} by weight)\n\n`;

    for (const f of topFacts) {
        const verLabel = f.verification_count > 0 ? `, verifications: ${f.verification_count}` : "";
        out += `### ${f.id} (weight: ${f.weight.toFixed(2)}${verLabel})\n`;
        out += `${f.statement}\n`;
        if (f.agents_must_know) {
            out += `> **Agents must know:** ${f.agents_must_know}\n`;
        }
        out += "\n";
    }

    return out;
}

async function main(): Promise<void> {
    const targetAgent = process.argv[2];
    const agents = targetAgent
        ? readAgentDefs().filter((a) => a.name === targetAgent)
        : readAgentDefs();

    if (agents.length === 0) {
        console.error(targetAgent
            ? `Agent not found: ${targetAgent}`
            : "No agents found. Check agents/ directory.");
        process.exit(1);
    }

    const db = await getMemoryDb();
    await ensureSchema(db);

    // Pre-fetch facts for all scopes
    const scopesNeeded = new Set<Scope>();
    for (const agent of agents) {
        for (const s of agent.homeScopes) { scopesNeeded.add(s); }
    }

    const factsByScope = new Map<Scope, FactRow[]>();
    for (const scope of scopesNeeded) {
        factsByScope.set(scope, await listFacts(db, { scope, limit: 50 }));
    }

    // Generate and write
    for (const agent of agents) {
        const pack = generateContextPack(agent, factsByScope);
        const outPath = join(AGENTS_DIR, agent.name, "SCOPE.md");
        writeFileSync(outPath, pack);
        console.log(`✓ Generated ${agent.name}/SCOPE.md`);
    }

    console.log(`\nDone. ${agents.length} context pack(s) generated.`);
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
